#!/bin/sh -ex

SRC=/usr/local/src
WEBROOT=/var/www/foodsoft
SECRET_KEY=turnkey1

/etc/init.d/mysql start

# get rid of sample app but store database config
mv $WEBROOT/config/database.yml /tmp/foodsoft_database.yml
rm -Rf $WEBROOT

# extract application to webroot
mkdir -p $WEBROOT
tar -zxf /usr/local/src/foodsoft* --strip-components 1 -C $WEBROOT

rm -f /usr/local/src/foodsoft*

# add database config 
cp /tmp/foodsoft_database.yml $WEBROOT/config/database.yml

cd $WEBROOT

# disable sharedlists in configuration, we don't use it here
# rename key instead of commenting to make it work too when it contains children
# (if it's a database.yml label, it may even break deployment)
sed -ri 's|^(\s*)(shared_lists:)|\1dont_use_\2|' $WEBROOT/config/app_config.yml.SAMPLE

# do not require ssl, since we start with an untrusted certificate
sed -ri 's|^(\s*config\.force_ssl\s*=\s*).*$|\1false|' $WEBROOT/config/environments/production.rb

# use existing MTA with sendmail
echo 'Foodsoft::Application.configure { config.action_mailer.delivery_method = :sendmail }' >>$WEBROOT/config/environments/production.rb

# add TurnkeyLinux credit (when a footer is available)
sed -ri 's|^((.*)\.pull-right)|\1= raw ("\&nbsp;on " + link_to("Turnkey Linux", "http://www.turnkeylinux.org"))\n\1|' $WEBROOT/app/views/layouts/_footer.html.haml 2>/dev/null || true

# set secret key for database setup
export SECRET_KEY_BASE=$SECRET_KEY

# install dependencies
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
gem install bundler

bundle install --without test development --deployment
bundle exec rake foodsoft:setup:stock_config RAILS_ENV=production

unset HTTP_PROXY

# setup database
bundle exec rake db:setup railties:install:migrations db:migrate RAILS_ENV=production
ln -s $NAME $WEBROOT

bundle exec rake assets:precompile RAILS_ENV=production

# configure permissions
mkdir -p $WEBROOT/tmp/pids
chown -R root:www-data $WEBROOT
chown -R www-data:www-data $WEBROOT/tmp
chown -R www-data:www-data $WEBROOT/log

# seed SECRET_KEY_BASE variable 
echo "export SECRET_KEY_BASE=$SECRET_KEY" | tee -a /root/.bashrc.d/foodsoft-secret /etc/apache2/envvars
chmod +x /root/.bashrc.d/foodsoft-secret

# start foodsoft worker by default
update-rc.d foodsoft-workers defaults

/etc/init.d/mysql stop

