#!/bin/bash -e
# set foodsoft admin password, email and variant

. /etc/default/inithooks
[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

SECRET=$(mcookie)$(mcookie)$(mcookie)

sed -i "s|SECRET_KEY_BASE.*|SECRET_KEY_BASE=$SECRET|" /root/.bashrc.d/foodsoft-secret
sed -i "s|SECRET_KEY_BASE.*|SECRET_KEY_BASE=$SECRET|" /etc/apache2/envvars

export SECRET_KEY_BASE=$SECRET

$INITHOOKS_PATH/bin/foodsoft.py \
    --pass="$APP_PASS" --email="$APP_EMAIL" 
